### ISSUE TITLE
Implement Boss SlurpiDurpiDurpDurp

### ISSUE THREAD

**Issue by fuchss-dominik** [fuchss-dominik/rekit-game#15]
Originally reported by: **Angelo Aracri (Bitbucket: [AnJ95](https://bitbucket.org/AnJ95), GitHub: [AnJ95](https://github.com/AnJ95))**

----------------------------------------

Boss version of Slurp

Consists of 6-8 green balls and 1 red ball.
The green balls make damage, the red ball can be damaged.
(ReactToCollision())

Periodically shoots green balls at player, that make damage while flying and stick to walls (They only slow the player while sticking to a wall)
(TimeDependency, Boss.target)

The Player can harm the boss only when there is just the red ball left.

After a few seconds, all the green balls go back to where they were and the boss behavior repeats itself

----------------------------------------
- Bitbucket: https://bitbucket.org/AnJ95/projectragnarok/issue/15

**Comment by AnJ95** [comment]
Too much work
