### ISSUE TITLE
Implement Boss WarpLord (WIP-Name)

### ISSUE THREAD

**Issue by fuchss-dominik** [fuchss-dominik/rekit-game#16]
Originally reported by: **Angelo Aracri (Bitbucket: [AnJ95](https://bitbucket.org/AnJ95), GitHub: [AnJ95](https://github.com/AnJ95))**

----------------------------------------

Bigger than regular Warps

He warps directly to the players position
(Boss.target.getPos())

However, he shows his next target with particle effects. So the player can see where the WarpLord is planning to go but can dodge by quickly moving.

Upon every warp, the WarpLord changes its color to one of red, blue or purple

Also, upon every warp he spawns a ball that has regular physics (=> gravity) and bounces on the floor (like the Player does in idle state)

The player can shot these balls around the room, they bounce of walls (entry angle = reflection angle)
(compare pos => calc angle => apply velocity)

The WarpLord only takes damage when he is hit with a ball with the same color he currently has, the balls otherwise disappear.

----------------------------------------
- Bitbucket: https://bitbucket.org/AnJ95/projectragnarok/issue/16

**Comment by AnJ95** [comment]
Too much work
