### ISSUE TITLE
Implement Boss CrazyRocketRobot

### ISSUE THREAD

**Issue by fuchss-dominik** [fuchss-dominik/rekit-game#17]
Originally reported by: **Angelo Aracri (Bitbucket: [AnJ95](https://bitbucket.org/AnJ95), GitHub: [AnJ95](https://github.com/AnJ95))**

----------------------------------------

Has a (robot-like) head and an iron bar below that holds 3 rockets.

His weak spot is his head, but he flies, so he cannot be hit.

He periodically shoots rockets.

The only way to harm him is to jump across the rockets to hit his head.

----------------------------------------
- Bitbucket: https://bitbucket.org/AnJ95/projectragnarok/issue/17

**Comment by AnJ95** [comment]
Is almost done, only some code beautification is todo
