### ISSUE TITLE
After death features

### ISSUE THREAD

**Issue by fuchss-dominik** [fuchss-dominik/rekit-game#2]
Originally reported by: **Angelo Aracri (Bitbucket: [AnJ95](https://bitbucket.org/AnJ95), GitHub: [AnJ95](https://github.com/AnJ95))**

----------------------------------------

Show score/highscore dependent death-messages.
Add countdown that restarts game

----------------------------------------
- Bitbucket: https://bitbucket.org/AnJ95/projectragnarok/issue/2

**Comment by AnJ95** [comment]
For the arcade levels we need a button menu after the game ends in general
Upon win:  Next, ArcadeMenu
Upon fail: Retry, ArcadeMenu

**Comment by matzebond** [comment]
On it.
Shouldn't be to different from db3a32b76717d20bd283ed25417d187a8f94754b

**Comment by matzebond** [comment]
After #34 #32 #31 this might be done
