### ISSUE TITLE
Controller is not debuggable

### ISSUE THREAD

**Issue by matzebond** [fuchss-dominik/rekit-game#30]
After reaching a break point in the Controller and continuing the Controller doesn't work anymore.
The game still runs, but inputs are ignored.

**Comment by fuchss-dominik** [comment]
I can't reproduce this issue. Where's the breakpoint? I've placed it at "handleEvent" and got events, resumed and got further events.

**Comment by AnJ95** [comment]
This happens to me a lot when switching windows while the game is still running.

**Comment by fuchss-dominik** [comment]
Resolved Issue. With last commit.
If you switch the window, you could select the canvas (but nobody has listened to the canvas)
