### ISSUE TITLE
ArcadeLevelManager

### ISSUE THREAD

**Issue by matzebond** [fuchss-dominik/rekit-game#31]
We need some kind of manager for the arcade levels

It's purpose would be:  
- [in the end menu][todo]: got to the next arcade level after the current one was completed ]
- show which levels are completed in the main menu

[todo]: https://github.com/fuchss-dominik/rekit-game/blob/master/project/logic/src/main/java/rekit/logic/scene/LevelScene.java#L205

**Comment by fuchss-dominik** [comment]
Currently there's no difference between custom levels and arcade levels. Do we need to make a difference?

**Comment by matzebond** [comment]
What are custom levels? Levels introduces by mods?
There should be (and is) a difference between the e.g. the infinite levels (infinite, lod, boss rush) and the arcade ones.

**Comment by fuchss-dominik** [comment]
Yes. (Levels which are located in the levels folder are loaded as arcade level)
Currently an Arcade Level can be infinite. (See last arcade level).

**Comment by fuchss-dominik** [comment]
LevelManager manages groups of ArcadeLevels
