### ISSUE TITLE
MainMenueScene: go directly to a submenu

### ISSUE THREAD

**Issue by matzebond** [fuchss-dominik/rekit-game#32]
After [finishing an arcade level][todo] we want to a menu entry which goes back to the arcade level selection not the top of the main menu.
Likewise after finishing the infinite level, boss rush and level of the day go back to the level selection

This could be done by sending an argument when creating a new MainMenueScene

[todo]: https://github.com/fuchss-dominik/rekit-game/blob/master/project/logic/src/main/java/rekit/logic/scene/LevelScene.java#L215

**Comment by fuchss-dominik** [comment]
We could save the state in the scene. And switch to the last state.

**Comment by matzebond** [comment]
cheap fix in 0e9c1a1a653a48f29d0762eca1532e9290fe9770

**Comment by AnJ95** [comment]
works
