### ISSUE TITLE
Make Scenes/GameObjects restartable

### ISSUE THREAD

**Issue by matzebond** [fuchss-dominik/rekit-game#33]
Since it's now possible to restart a level from the pause and end menu, we should check that this works correctly for all Scenes and  every GameObject (especially bosses and one time stuff)

we didn't really account for this see a7e703d986df4cdb3ada09cdb9a4effad9697545

use the init method of GameObject

**Comment by fuchss-dominik** [comment]
Just invoke #reset() to the Level of the Scene and all should work.

**Comment by matzebond** [comment]
Well this won't work if stuff like the player does not reset properly.
This issue was created as a reminder. Once all levels (arcade + bosses) are tested we can ofc close this.

**Comment by fuchss-dominik** [comment]
Invoking reset, will recreate all structures, so the Player should be the only special instance.

**Comment by matzebond** [comment]
True that
the player resetting problem was a exception

**Comment by fuchss-dominik** [comment]
To Check: Check whether Queues will be cleaned upon reset (otherwise Elements could be rendered at the last position of the level (?!)
