### ISSUE TITLE
Arcade Structure

### ISSUE THREAD

**Issue by AnJ95** [fuchss-dominik/rekit-game#35]
The arcade levels are currently a mess and id like to have them in logic order introducing special block, enemy etc step after step.

Id propose to make levels in packs of ten, with rising difficulty and boss at the end introducing only a few features each.

Judging by the current amount of bosses and enemys we can make 2 packs = 20 levels

For experimentation me might want to think of creating a debug-mode-only -21.-level

**Comment by fuchss-dominik** [comment]
We need to set some names for the levels. But then I think the 2 packs are enough.
