### ISSUE TITLE
Update Infinite Mode

### ISSUE THREAD

**Issue by AnJ95** [fuchss-dominik/rekit-game#36]
We have tons of functionality not used by the infinite level.
Platforms,  Cannons and PickUps could serve very well.

So @matzebond @fuchss-dominik go ahead and add a few Structures :P

**Comment by AnJ95** [comment]
Ping @matzebond @fuchss-dominik

**Comment by AnJ95** [comment]
ping

**Comment by matzebond** [comment]
pong

**Comment by fuchss-dominik** [comment]
Version 1.0 has enough structures so far... reopen if necessary for further releases
