### ISSUE TITLE
MrRekt glasses

### ISSUE THREAD

**Issue by fuchss-dominik** [fuchss-dominik/rekit-game#4]
Originally reported by: **Angelo Aracri (Bitbucket: [AnJ95](https://bitbucket.org/AnJ95), GitHub: [AnJ95](https://github.com/AnJ95))**

----------------------------------------

Player loose glasses on hit (show tiny eys while invincible)

----------------------------------------
- Bitbucket: https://bitbucket.org/AnJ95/projectragnarok/issue/4

**Comment by AnJ95** [comment]
Tried it out and it looks weird
